spring.application.name=CadastroDeNinjas
spring.datasource.url=jdbc:h2:mem:ninjadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Isso permite ver o console do H2 no navegador em /h2-console
spring.h2.console.enabled=true